stages:
  - build
  - test
  - deploy
  - delete

default:
  tags:
    - docker
  image:
    name: devops.local.lan:5050/gitlab-instance-bd9918c6/docker-terraform-image:main-28
  before_script:
  - |
    echo "-----BEGIN CERTIFICATE-----
    MIIFdTCCA12gAwIBAgIULOUmr96cRVRB7OoRzVTqO0QWwsUwDQYJKoZIhvcNAQEN
    BQAwITEfMB0GA1UEAxMWRGV2T3BzIEludGVybWVkaWF0ZSBDQTAeFw0yMjA5MTUx
    ODM3MDBaFw0zMjA5MTIxODM3MDBaMBsxGTAXBgNVBAMTEGRldm9wcy5sb2NhbC5s
    YW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDmu/XXsFp4KtDQetTu
    lwmbVJUi+k/lp11UH4WSyPl5MlRy8Xc2EJL/NI9P8PzLwbOTg4F6MvuxXCZsjl3Z
    u57Uf2r22oH0lEh1xlWpT3dc0/32TBEST5UG4ibQ+jp8bk8uxxEX8xpZJ91ocZqK
    /J+GLRLSWQsOCyk4Djvj5/6aGiO8oj1xyWnJFptPQO10kVZFDZ4ie9RBS85ZUmA/
    A4v870t78L8+d6NFRbk0+UHRMcapDCxFGZJBZA2me2L46wnEQ8Mdo3AYlxEHEmkE
    8flNp2Ir5C7OK7GksvAOaAFAxWFvrtWNUBEpTA6U2LShy1+fpd9kPmnNgirLzE2F
    CzXxBbaSCSW8ph8drLWRqgxg/Te8IriV5bPFPG2MjAAJeYT//RCLGhl4YJSQPMpC
    QPlTgSOtGwD04JuQWSROYAuoFqbJydncIm63hIahaokOAA6Up22vyFcYd53O4Ig9
    T0BMjtGDzlE9fxyzhh2ERy0Fit8RsAWN7PQn4xzcKwEskpYhii0oysH0B6FzZJZK
    fan8aBXWd8EFevBGkwn466ou8c0OPvT4i+fYsSAZ9GZVXPeP/Qbph6nBaXSYJGbj
    sw+CASb16Df1E1gjTJEKO229siEbJeUcSIMoQweuItLOU5Of5uvPoIul/ww8Gx2n
    9YZsp+dZefhPziMHfFLmYwMWWwIDAQABo4GqMIGnMA4GA1UdDwEB/wQEAwIFoDAT
    BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQDOClw
    HTTGmU/8Ct/jpvHW//lpcjAfBgNVHSMEGDAWgBR00Q3EB/00aAnevLjdZmwtw6WM
    PzAyBgNVHREEKzApghBkZXZvcHMubG9jYWwubGFugglsb2NhbGhvc3SHBAoUHgqH
    BH8AAAEwDQYJKoZIhvcNAQENBQADggIBAJWwJfeD2cNqJo6eKSwmZRs4u8GK/FsL
    GV/mZQaChwKlqPZ63xdtJ8tKAN25z/AtYg9nlEEhPbk9pjLVBL9ohiZhelvh1MNf
    BwqLOEHAdM/Gy5PfkGTL7UUVi9L4YMqgjYHGkEyTX4I+Z2Lr0eSuc58lhVBwymTf
    XUyJ8lYfjV1fHCcTUIN+7D9QzC4Uo6SXVH9LCMuwmf0F9qFvIhYfpxGH2gSlTlvO
    X80tkINqpMfW2gGUGwhGNJg35SQaKV3CmxLsQwUfiMqit92CmfiF8M3ZIHS7kkU5
    U6efz1WkMeckloHiiSDQhnd46qVAlCbz34eEAOspHJ6xCYoEZdamdA7UHJZ1Ls4+
    aDCTz60S3rfuO8N6tKyklOXa+oqHVaUtRoCIffdOj69t6wJN8xtfwwTUzbH1oPz0
    YiKemZ42aATTE/gQnYUvxpcC2kJVJsDZy76wledpvS9/mN5n3AzfJ6npZ/KchWsp
    YHPje4UUE+YoI4jrwBp44ALtzR9ctDiR5Pg+2nVCPo0FRN8wwVa2VoYUsDa6hHPu
    8KCRAcTZcjz50OEAmnBV7NcfyWvOWju693294HW1bTiWpdTk3dcR/zd8h6323yNC
    zshlqhUcgJ1QriR9gyOQJa0XXJl+oRByzLGpFutQIba9rGlxRU1ZHIlMd8yw/kms
    /3D6heia7ctL
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFYTCCA0mgAwIBAgIUTmRfC+eQxw1LASL0ZM5NcUpXPwEwDQYJKoZIhvcNAQEN
    BQAwTzELMAkGA1UEBhMCRlIxDjAMBgNVBAcTBVBhcmlzMQ8wDQYDVQQKEwZEZXZP
    cHMxHzAdBgNVBAMTFkRldk9wcyBNYWNoaW5lIFJvb3QgQ0EwHhcNMjIwOTE1MTgz
    NzAwWhcNMzIwOTEyMTgzNzAwWjAhMR8wHQYDVQQDExZEZXZPcHMgSW50ZXJtZWRp
    YXRlIENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtnfpBd5arpYe
    +kOtrPUf9Sq5bm9XZ3fNQAy21iv68i+hxGP49aKIhY76qRpwX8OJolu0rXA9HrZL
    gAhNHrqsh7ZwaZwZw6aLfLPov2uBErw5i0vsjVx8OIR66b6LrjZ9BBf1NCAIqDSE
    rskmP8AY1txiy2sZcxIEuuATa8Roovw0nHLf3u1pvJavHKqvcin0lDuP5fIqYHyW
    hBVykssT3ZQaIkaGgD1Duack7b3/X4kmb1YzYml08kVXaKT53ih4bKZgK1z1WeP4
    Vj7QGdQmr/kNc9BfBLF8gDQNacla1zrpnFb6gsOjmhKP32bbtzJJdByUBkt9NVKN
    GpLn69/e5IZEf7iPHYT5YIgd1J5/uz5jCuDnj0TAY3VMKADBkFG2zzS/lHrJIq8I
    CIHoY1r63XdGcIyRAHp4kMZOxclUeDVI94cHsXFl91sWoEyNTD2mbcP7py0d3gSe
    mMm4wmlLV4e7IIcJiiKpiyaXr+Gx5XzrCs/I6tsnl37qAl33lOLw9jK0XYRwx3Mm
    7mt48bP9TCFFh+WWwQvmQiPgK9G7Mn+nfme3pd5ShMAD0aBfGZ6evyy5tTkcnn1e
    JtjK2PqrulIWgCff5exgyd5QxqLe/9vXx7F0Q8CEtTj5rcP5Jj4E6WFIa9TZAEwV
    N0B7fHYw5YbAMqolsXsRZbSSXI7rpf8CAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGG
    MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFHTRDcQH/TRoCd68uN1mbC3DpYw/
    MB8GA1UdIwQYMBaAFIQlE9QDAkObFYn2yt/K48/pUJsVMA0GCSqGSIb3DQEBDQUA
    A4ICAQB/3BVIQipcNAG+mfSy9q3PLarog11ynBpfGJRemA4FDC0gPAhTXG2/h/ZY
    0ZoOe33pQw2X6Y+5iTtdmUGV1GPuM9CT4wYognWNFEbinTAm+ZeEDN/AKdSDX+pp
    ylkXMY4QHmMtVzm3Ik2LyCfS334Upf6W665ySEvJkpu4utgjQOh+vGhMKZtUS0Wk
    IxJzPgIZy2nHcoTnUKBRyra2u6qjT1pmrkumI83xk8xVr96MF+6Ui1GQ6RygIR2g
    smXn7huEz6fn/UHaIHyZ9s5wzqAwmus35yzTmRh6/voNXm+9y/qClUFcxcgecCNp
    5SH1wKNGpJKWBpttePMvxTee5DAUaXvPmAJBG3NcS/+z5wj1Y/9bRgzqnhR1sHsc
    MJrHr4mDzhm/xzlDqpO6sbDmj9JZSBelWP4AjGl4AsHddj6KD205Y9i7+p2plOjj
    inH6Pl3I68ndu+FCa4TXkkSJNv/2Shc844PW8xVdIOpQyFP2xUJFSpQAiSz1zabS
    mGpE/t+AxYDKgsVHmiLmMOORKddaNjQEcokmIoriwIm/kU7kOrsR21iqWIKwsML8
    RWjcG8KDARBtkBXQ15qAirBnJ7PVT1fvlhNKf1+CR6DKLm7HRpEJWuG8oaH8FxGd
    3e/GwIITtIxC7IEfLkQwRElBWMAAQx5Cd3UNDPh7JHdSGKl3uw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFbjCCA1agAwIBAgIUOaS1nndKVWJp1N1Yu3MDAHiT9qwwDQYJKoZIhvcNAQEN
    BQAwTzELMAkGA1UEBhMCRlIxDjAMBgNVBAcTBVBhcmlzMQ8wDQYDVQQKEwZEZXZP
    cHMxHzAdBgNVBAMTFkRldk9wcyBNYWNoaW5lIFJvb3QgQ0EwHhcNMjIwOTE1MTgz
    NzAwWhcNMzIwOTEyMTgzNzAwWjBPMQswCQYDVQQGEwJGUjEOMAwGA1UEBxMFUGFy
    aXMxDzANBgNVBAoTBkRldk9wczEfMB0GA1UEAxMWRGV2T3BzIE1hY2hpbmUgUm9v
    dCBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPMeSPusemwr4scD
    4kcUGIFhH2BAwAO3vChkVXdUtcndqqhecUont+rU/zA39TORpUvbJDZHDpQcXdcg
    bENWO1yvGHImbABwiKnhAj88TA3K3iBvfzD+6/0XqYr8tEX9a7Aa8eKK6P+3fhQp
    EvjOOa59l7VMffoxfm3wRcSNDsC/OzFiMUvq2eK4z7GH9mHGGixO9SCTPU9ytXh+
    pzs9+PJU5V515Gg4Uyy5+CW7wifyoVP3AAOOPMYRIQL30qqKLHPVLpLEaK9Pec9y
    VrQotTYbFfsWJbXh60MbSPG2e++XkK5Zm5gketjP/PEPTUw2QtSEYyhI/a6IaG5B
    rBI6kXnz9/x+vPisSA1K62yVhD8yARY+ocjgWw1pSUpd7jusZd7hS5EP7A0EiwUR
    B4eEGQZReX2b3a2FmrKErkahk2g1fq6gkG9kTb6UxpB0ZqSs19z429aK0pM/RElc
    ugxZ+lUZIuPRBa1JKe3he8AxeDaWupcL+B2GPTYYJXljs3l/xZ/fi1/NB3+gj2ge
    gYNAXDTWUIbs5B8troN2muUx0LJYEloLHXrhkrqtDygown90PJ3DLTEWj7JDfpiI
    JtMVj/xvXYs9jRxQ4qihkmyptCHNJo1CnvKgFeWhjqYhkQZAMrCw9DSCrMt5bCwc
    yR7whAXC9AY/aV59yeCSVHIMxNZlAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSEJRPUAwJDmxWJ9srfyuPP6VCbFTAN
    BgkqhkiG9w0BAQ0FAAOCAgEAY71/36Eim3ilTBTgTqZta1I9jU7uk1uWgJA9uB99
    Z5rlZboilrGjzlxPb2TLcbRTKOqfS5FJAbtZOIcFX+MXgWwqlns1RJ11xdzaDnGF
    4Om2UmcNvHrq+VSfoogD9lpKquKM+B6cPlcMuqxztPlbQY2+k62e5yB8iQJI6Abo
    oFm5Xct+Oqx0g4h9a+e3EeXW4G/kCPV96ueVSQUqm2RJr4n2uNLk2306wf9wzvgj
    wbk+oV8nl4T9vavncLklGQKZ66HsLSEfSPk0NWkevl+fz9Xvg6XKnlO3juNC9zQh
    yz7VqvECuI3WDSQiGKKpYM1DQf6FZzT2OYLoNRVJZnVTmiWn7SsUGCMVZm3XVCvZ
    va9rLlBOxgNNM0QbDTwiPMu4KLbRDYtE2dBd5cbehCuYsgq2B1alwYGY9jQBhxoq
    SiDFx9LJjIwIez+Uex3vR3nV94h80J8XoCnR/zfL2KrlO3IGjIW36DBphmTcdPAV
    nxT9gKOKiGY5V0eJ8TqEGNMSz/JsEp703N4hpPasgkL275VAlzkOW/sJr8FtbSFl
    Cu+Pxg6G25/CxhSLdYiS7D/30U4Q9gJz6PSKj+nzsoisl+A79l7RguoxNuBJI1UI
    9nu5q+OYoUEZ05LB7zhd+TGkBhj6IHzUw051DnBTPexHD5aBxcpvTylboQ77+fPC
    JbY=
    -----END CERTIFICATE-----" >> /etc/ssl/certs/repopierre-ca-cert-bundle.crt
    terraform init \
      -backend-config=address=https://devops.local.lan/api/v4/projects/2/terraform/state/old-state-name \
      -backend-config=lock_address=https://devops.local.lan/api/v4/projects/2/terraform/state/old-state-name/lock \
      -backend-config=unlock_address=https://devops.local.lan/api/v4/projects/2/terraform/state/old-state-name/lock \
      -backend-config=username=root \
      -backend-config=password=glpat-2KtmhDcszDBBmThbL9mv \
      -backend-config=lock_method=POST \
      -backend-config=unlock_method=DELETE \
      -backend-config=retry_wait_min=5

validate-job:
  only:
    - main
  stage: test
  tags:
    - docker
  script:
    - terraform validate

plan-job:
  only:
    - main
  stage: test
  tags:
    - docker
  script:
    - terraform plan

deploy-job:
  only:
    - main
  stage: deploy
  tags:
    - docker
  script:
    - terraform apply -auto-approve
    - git config --global http.sslCAInfo /etc/ssl/certs/repopierre-ca-cert-bundle.crt
    - git clone https://gitlab-ci-token:glpat-GHPnhr7yK1DcuFB--2iz@devops.local.lan/gitlab-instance-bd9918c6/k8s-common-tools.git
    - kubectl --kubeconfig=kubeconfig apply -f k8s-common-tools/

delete-job:
  only:
    - main
  stage: delete
  when: manual
  tags:
    - docker
  script:
    - terraform destroy -auto-approve
